version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/Hello.World"
      - "/test/Hello.World.Tests"
    schedule:
      interval: "daily"
    groups:
      nuget-packages:
        patterns:
          - "*"
